source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

# from accounts.views import login_view, logout_view
from accounts.views import RegisterView, UserProfileView, UpdateUserView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegisterView.as_view(), name="registration"),
    path('<int:pk>/', UserProfileView.as_view(), name="user-profile"),
    path('update/', UpdateUserView.as_view(), name="update-user"),
    path('change-password/', UserPasswordChangeView.as_view(), name="change-password")
]

source/hello/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, TaskView, TaskDeleteView, TaskCreateView, TaskUpdateView, ProjectList, ProjectView, \
    ProjectCreate, ProjectUpdate, ProjectDelete, UsersListView, ChangeUsersInProjectView

app_name = 'webapp'

urlpatterns = [
    path('', ProjectList.as_view(), name="project_list"),
    path('project/<int:pk>/', ProjectView.as_view(), name="project_view"),
    path('project/add/', ProjectCreate.as_view(), name="project_add"),
    path('project/<int:pk>/update/', ProjectUpdate.as_view(), name="project_update"),
    path('project/<int:pk>/delete/', ProjectDelete.as_view(), name="project_delete"),
    path('tasks', IndexView.as_view(), name="index"),
    path('task/<int:pk>/', TaskView.as_view(), name="task_view"),
    path('project/<int:pk>/tasks/add/', TaskCreateView.as_view(), name="project_task_add"),
    path('project/<int:pk>/task/delete/', TaskDeleteView.as_view(), name="task_delete"),
    path('project/<int:pk>/task/update/', TaskUpdateView.as_view(), name="task_update"),
    path('project/<int:pk>/change-users/', ChangeUsersInProjectView.as_view(), name="change_project_users"),
    path('users/', UsersListView.as_view(), name='users_list')
]

source/webapp/models.py
from datetime import date

from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

from webapp.validators import MinLengthValidator, MaxLengthValidator

# Create your models here.

User = get_user_model()


class Status(models.Model):
    name = models.CharField(max_length=200, verbose_name='Статус')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        db_table = 'status'
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class Type(models.Model):
    name = models.CharField(max_length=300, verbose_name='Тип')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        db_table = 'type'
        verbose_name = 'Тип'
        verbose_name_plural = 'Типы'


class Task(models.Model):
    summary = models.CharField(max_length=255, null=False, blank=False, verbose_name='Заголовок',
                               validators=(MinLengthValidator(2),))
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание',
                                   validators=(MaxLengthValidator(2000),))
    status = models.ForeignKey('webapp.Status', related_name='tasks', on_delete=models.PROTECT, verbose_name='Статус')
    type = models.ManyToManyField('webapp.Type', related_name='tasks')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    project = models.ForeignKey('webapp.Project', related_name='tasks', on_delete=models.CASCADE, verbose_name='Проект')

    def __str__(self):
        return f"{self.pk}.{self.summary}"

    class Meta:
        db_table = 'tasks'
        verbose_name = 'задача'
        verbose_name_plural = 'задачи'
        permissions = (
            ("add_task_in_own_project", "Добавлять задачи в свой проект"),
            ("change_task_in_own_project", "Редактировать задачи в своем проекте"),
            ("delete_task_in_own_project", "Удалять задачи в своем проекте"),
        )


class Project(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False, verbose_name='Название')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    date_start = models.DateField(default=date.today, verbose_name='Дата начала')
    date_end = models.DateField(null=True, blank=True, verbose_name="Дата окончания")
    users = models.ManyToManyField(
        User,
        related_name="projects",
        default=1,
    )

    def get_absolute_url(self):
        return reverse("webapp:project_view", kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.name}"

    class Meta:
        db_table = 'projects'
        verbose_name = 'проект'
        verbose_name_plural = 'проекты'
        permissions = (
            ("change_user_in_own_project", "Изменять список пользователей в своем проекте"),
        )

source/webapp/forms.py
from django import forms

from django.forms import widgets


from webapp.models import Task, Type, Project


class TaskForm(forms.ModelForm):
    type = forms.ModelMultipleChoiceField(queryset=Type.objects.all(), label="Тип", widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Task
        fields = ("summary", "description", "status", "type")


class SearchForm(forms.Form):
    search = forms.CharField(max_length=30, required=False, label='Поиск')


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        exclude = ("users",)


class ProjectUsersForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ("users",)

source/webapp/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.views import View
from django.views.generic import TemplateView, ListView

from webapp.forms import TaskForm, SearchForm
from webapp.models import Task


class IndexView(ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'index.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.form = self.get_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset.order_by('-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = SearchForm()
        if self.search_value:
            context['form'] = SearchForm(initial={"search": self.search_value})
            context['search'] = self.search_value
        return context

    def get_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get('search')


class TaskView(TemplateView):
    template_name = 'task_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = get_object_or_404(Task, pk=kwargs.get("pk"))
        context['task'] = task
        return context


class TaskCreateView(View):
    def get(self, request, *args, **kwargs):
        form = TaskForm()
        return render(request, 'task_create.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = TaskForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        return render(request, "task_create.html", {'form': form})


class TaskUpdateView(View):
    def get(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs.get("pk"))
        form = TaskForm(initial={
            "summary": task.summary,
            "description": task.description,
            "status": task.status,
            "type": task.type.all()
        })
        return render(request, 'task_update.html', {'task': task, "form": form})

    def post(self, request, *args, **kwargs):
        form = TaskForm(data=request.POST)
        task = get_object_or_404(Task, pk=kwargs['pk'])
        if form.is_valid():
            type = form.cleaned_data.pop('type')
            task.type.set(type)
            task.summary = form.cleaned_data.get('summary')
            task.description = form.cleaned_data.get('description')
            task.status = form.cleaned_data.get('status')
            task.save()
            return redirect('index')
        return render(request, 'task_update.html', {"task": task, "form": form})


class TaskDeleteView(View):
    def get(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs.get('pk'))
        return render(request, "task_delete.html", {"task": task})

    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=kwargs['pk'])
        task.delete()
        return redirect("index")

source/webapp/views/projects_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import ProjectForm
from webapp.models import Project


class ProjectList(ListView):
    model = Project
    template_name = "projects/project_list.html"
    context_object_name = 'projects'
    paginate_by = 3


class ProjectView(DetailView):
    model = Project
    template_name = 'projects/project_view.html'
    context_object_name = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tasks = self.object.tasks.all()
        context['tasks'] = tasks
        return context


class ProjectCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'webapp.add_project'
    model = Project
    form_class = ProjectForm
    template_name = 'projects/project_create.html'

    def form_valid(self, form):
        response = super(ProjectCreate, self).form_valid(form)
        self.object.users.add(self.request.user)
        return response


class ProjectUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'webapp.change_project'
    model = Project
    template_name = 'projects/project_update.html'
    form_class = ProjectForm
    context_object_name = 'project'

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})


class ProjectDelete(PermissionRequiredMixin, DeleteView):
    permission_required = "webapp.delete_project"
    model = Project
    template_name = "projects/project_delete.html"
    context_object_name = 'project'
    success_url = reverse_lazy('webapp:project_list')

source/webapp/views/tasks_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView

from webapp.forms import TaskForm, SearchForm
from webapp.models import Task, Project


class IndexView(ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'tasks/index.html'
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        self.form = self.get_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset.order_by('-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = SearchForm()
        if self.search_value:
            context['form'] = SearchForm(initial={"search": self.search_value})
            context['search'] = self.search_value
        return context

    def get_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get('search')


class TaskView(TemplateView):
    template_name = 'tasks/task_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = get_object_or_404(Task, pk=kwargs.get("pk"))
        context['task'] = task
        return context


class TaskCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'webapp.add_task_in_own_project'
    model = Task
    form_class = TaskForm
    template_name = 'tasks/task_create.html'

    def has_permission(self):
        project = get_object_or_404(Project, pk=self.kwargs.get("pk"))
        return super().has_permission() and self.request.user in project.users.all()

    def form_valid(self, form):
        project = get_object_or_404(Project, pk=self.kwargs.get("pk"))
        form.instance.project = project
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={"pk": self.object.project.pk})


class TaskUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = "webapp.change_task_in_own_project"
    model = Task
    template_name = 'tasks/task_update.html'
    form_class = TaskForm
    context_object_name = 'task'

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={"pk": self.object.project.pk})

    def has_permission(self):
        return super().has_permission() and self.get_object().project.users.filter(pk=self.request.user.pk).exists()


class TaskDeleteView(PermissionRequiredMixin, DeleteView):
    model = Task
    template_name = "tasks/task_delete.html"
    context_object_name = 'task'
    success_url = reverse_lazy('webapp:project_list')
    permission_required = "webapp.delete_task_in_own_project"

    def has_permission(self):
        return super().has_permission() and self.get_object().project.users.filter(pk=self.request.user.pk).exists()


# class TaskUpdateView(View):
#     def get(self, request, *args, **kwargs):
#         task = get_object_or_404(Task, pk=kwargs.get("pk"))
#         form = TaskForm(initial={
#             "summary": task.summary,
#             "description": task.description,
#             "status": task.status,
#             "type": task.type.all()
#         })
#         return render(request, 'tasks/task_update.html', {'task': task, "form": form})
#
#     def post(self, request, *args, **kwargs):
#         form = TaskForm(data=request.POST)
#         task = get_object_or_404(Task, pk=kwargs['pk'])
#         if form.is_valid():
#             type = form.cleaned_data.pop('type')
#             task.type.set(type)
#             task.summary = form.cleaned_data.get('summary')
#             task.description = form.cleaned_data.get('description')
#             task.status = form.cleaned_data.get('status')
#             task.save()
#             return redirect('index')
#         return render(request, 'tasks/task_update.html', {"task": task, "form": form})


# class TaskDeleteView(View):
#     def get(self, request, *args, **kwargs):
#         task = get_object_or_404(Task, pk=kwargs.get('pk'))
#         return render(request, "tasks/task_delete.html", {"task": task})
#
#     def post(self, request, *args, **kwargs):
#         task = get_object_or_404(Task, pk=kwargs['pk'])
#         task.delete()
#         return redirect("index")

source/webapp/views/users.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.urls import reverse
from django.views.generic import ListView, UpdateView

from webapp.forms import ProjectUsersForm
from webapp.models import Project

User = get_user_model()


class ChangeUsersInProjectView(PermissionRequiredMixin, UpdateView):
    model = Project
    template_name = 'users/change_users.html'
    form_class = ProjectUsersForm
    permission_required = "webapp.change_user_in_own_project"

    def get_success_url(self):
        return reverse('webapp:project_view', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return super().has_permission() and self.request.user in self.get_object().users.all()


class UsersListView(PermissionRequiredMixin, ListView):
    model = User
    template_name = 'users/users_list.html'
    context_object_name = "users_obj"
    permission_required = "accounts.can_look_list_of_users"

source/webapp/templates/projects/project_create.html
{% extends 'base.html' %}

{% block title %}Add project{% endblock %}
{% block nav %}{% endblock %}
{% block content %}
    <h1>Create Project</h1>
    <form method="POST">
        {% include "partial/form.html"  with button_text="Create" %}
    </form>
    <br>
    <a href="{% url "webapp:project_list" %}">Return to projects</a>
{% endblock %}

source/webapp/templates/projects/project_delete.html
{% extends 'base.html' %}

{% block nav %}{% endblock %}

{% block content %}
    <form action="{% url "webapp:project_delete" project.pk %}" method="POST">
    {% csrf_token %}
        <h2>Are you sure want to delete {{ project.name }} ?</h2>
        <input type="submit" value="Yes">
    </form>
    <button><a class="no_button" href="{% url 'webapp:project_list' %}">No</a></button>
{% endblock %}

source/webapp/templates/projects/project_list.html
{% extends 'base.html' %}

{% block content %}

    {% include "partial/list_project.html" %}
{% endblock %}

source/webapp/templates/projects/project_update.html
{% extends 'base.html' %}

{% block title %}Update project{% endblock %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:project_view' project.pk %}">Return to project</a>
    </li>
{% endblock %}
{% block content %}
    <h1>Update Project</h1>
    <form method="POST">
        {% include "partial/form.html" with button_text="Update" %}
    </form>
    <br>
    <a href="{% url "webapp:project_list"  %}">Return to projects</a>
{% endblock %}

source/webapp/templates/projects/project_view.html
{% extends 'base.html' %}

{% block title %}Project {{ project.pk }}{% endblock %}
{% block nav %}
    {% if user.is_authenticated %}
        {% if perms.webapp.add_task_in_own_project and request.user in project.users.all %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:project_task_add' project.pk %}">Add Task</a>
            </li>
        {% endif %}
    {% if perms.webapp.change_project %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:project_update' project.pk %}">Update Project</a>
    </li>
        {% endif %}
        {% if perms.webapp.delete_project %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:project_delete' project.pk %}">Delete Project</a>
    </li>
        {% endif %}
        {% if perms.webapp.change_user_in_own_project %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'webapp:change_project_users' project.pk %}">Add users in project</a>
            </li>
        {% endif %}
    {% endif %}
{% endblock %}
{% block content %}
    <h1>{{ project.name}}</h1>
    <p>Дата начала:{{ project.date_start}}</p>
    <p>Дата окончания: {% if project.date_end %}{{ project.date_end }}{% endif %} </p>
    <p>Описание:{{ project.description }}</p>
    <h6>Пользователи:{% for user_obj in project.users.all %}<a href="{% url 'accounts:user-profile' user_obj.id %}">{{ user_obj.username }}</a>{% if not forloop.last %},{% endif %}
    {% empty %}
            <p>No users yet.</p>
    {% endfor %}
    </h6>
    <h6>Tasks:</h6>
    <div>
        {% for task in tasks %}
        <div class="card border-success" style="width: 18rem;">
          <div class="card-body text-success">
              <h5 class="card-title">{{ task.summary }}</h5>
              <h6 class="card-subtitle mb-2 text-muted">Тип:{% for type in task.type.all %}{{ type.name }}{% if not forloop.last %},{% endif %}{% endfor %}</h6>
              <p class="card-text">Статус: {{ task.status.name }}</p>
              <a href="{% url "webapp:task_view" task.pk %}" class="card-link">More...</a>
              {% if user.is_authenticated %}
                  {% if perms.webapp.delete_task_in_own_project and request.user in project.users.all %}
                        <a href="{% url "webapp:task_delete" task.pk %}" class="card-link">Delete</a>
                  {% endif %}
                  {% if perms.webapp.change_task_in_own_project and request.user in project.users.all %}
                        <a href="{% url "webapp:task_update" task.pk %}" class="card-link">Update</a>
                  {% endif %}
              {% endif %}
          </div>
        </div>
        {% empty %}
            <p>No tasks yet.</p>
        {% endfor %}
    </div>
    <br>
    <a href="{% url "webapp:project_list" %}">Return to projects</a>
{% endblock %}